name: AllergyLab CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: build docker image
      run: |
           cd Part7a
           docker build -t ${{secrets.ZIZUQUANTIC}}/al-app:latest ./app
           docker build -t ${{secrets.ZIZUQUANTIC}}/al-db-loder:latest ./db-loder
           docker build -t ${{secrets.ZIZUQUANTIC}}/al-email:latest ./email